config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'

  get 'relationships/destroy'

  root to: 'articles#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get get'/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :articles do
    resources :comments
  end

  resources :relationships, only: [:create, :destroy]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
  validates :body, presence: true, length: {minimum: 20}
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_owner, only: [:edit, :destroy]
  def show
    # @comment = Comment.find(params[:id])
    
  end

  def new
    @article = Article.find(params[:article_id])
    # @comment = @article.comments.new
  end

  def create
    @user = current_user
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    @comment.user_id = current_user.id
#    @comment.save!
    @comments = @article.comments

    respond_to do |format|
      if @comment.save
        format.html {redirect_to @article}
        format.js
      else
        flash[:warning] = "You have to login to post your comment"
      end 
    end

  end
    
  
  def edit
    respond_to do |format|
      format.html  
      format.js  
    end
    # @article = Article.find(params[:article_id])
    # @comment = @article.comments.find(params[:id])
  end

  def update
    if @comment.update(comment_params)
      respond_to do |format|
        format.html do  
          flash[:success] = "Edited !"
          redirect_to article_path(@article)
        end
        format.js   
      end
    else
      render 'edit'
    end
  end

  def destroy
    # @article = Article.find(params[:article_id])
    # @comment = @article.comments.find(params[:id])
    if @comment.destroy
      @comments=@article.comments
      respond_to do |format|
        format.html do
          flash[:warning] = "Deleted! this comment"
          redirect_to article_path(@article)
        end
        format.js  
      end
    else
      flash[:info] = "Cant delete without login"
    end
  end
  private
  def comment_params
    params.require(:comment).permit(:commenter, :body, :article_id, :user_id)
  end

  def set_comment
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
  end

  def check_owner
    if current_user.id != @comment.user_id 
      flash[:warning] = "Sorry, only owner can do this thing!"
      redirect_to articles_path
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id = "show-comment-<%=comment.id%>">
  <%= link_to comment.user.name, user_path(comment.user) %>

  <%= comment.body %>

  <br>
  <%= time_ago_in_words(comment.created_at) %> ago

  <% if user_signed_in? && session[:user_id] == comment.user.id %>
  <!-- <%= session[:user_id] %>
   <%= comment.user.id %> -->
  <%= link_to 'Edit', edit_article_comment_path(comment.article_id, comment), remote: true %>
  <%= link_to 'Delete', article_comment_path(comment.article_id, comment),remote: true, method: :delete, data: {confirm: 'Do you want to delete this comment?'} %>
  <% end %>
</div>

app/views/comments/_editform.html.erb
<%= form_for [@comment.article_id, @comment],remote: true,html:{ class: "edit-comment-form form-group"}, url: article_comment_path(@comment.article_id, @comment) do |f| %>
  <fieldset class = "form-group">
    <%= f.text_area :body , class: "form-contrl"%>
  </fieldset>

  <fieldset class = "form-group">
    <%= f.submit %>
  </fieldset>
<% end %>

app/views/comments/_form.html.erb
<!-- <h1> Form for comment </h1> -->
<%= form_for [ @article, @article.comments.new], remote: true, html: {id: "create-comment-form"} do |f| %>
  <fieldset class = "form-group">
    <ol>
      <li class= "form-group">
        <%= f.text_area :body, rows: 2, cols: 60, placeholder: "Write a comment...", id: "comment-body", class: "form-control" %>
      </li>
      <li class= "form-group">
        <%= f.submit 'Post Comment',id: "post-comment", class: 'btn btn-info' %>
      </li>
    </ol>
  </fieldset>
<% end %>

app/views/comments/_newcomment.html.erb
<div id = "show-comment-<%=@comment.id%>">
  <%= link_to @comment.user.name, user_path(@comment.user) %>

  <%= @comment.body %>

  <br>
  <%= time_ago_in_words(@comment.created_at) %> ago

  <% if user_signed_in? && session[:user_id] == @comment.user.id %>
  <%= link_to 'Edit', edit_article_comment_path(@comment.article_id, @comment), remote: true %>
  <%= link_to 'Delete', article_comment_path(@comment.article_id, @comment),remote: true, method: :delete, data: {confirm: 'Do you want to delete this comment?'} %>
  <% end %>
</div>

app/views/comments/create.js.erb
$('#show-comments').append("<%= j render 'comments/newcomment' %>");
$('#comment-body').val("");
$('#comment-body').focus();

app/views/comments/destroy.js.erb
$('#show-comments').html("<%= j render @comments %>");
$('#show-comment-<%= @comment.id %>').remove();

app/views/comments/edit.js.erb
$('#show-comment-<%=@comment.id%>').html("<%= j render 'comments/editform' %>");
$('#show-comment-create-form').hide();

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/comments/update.js.erb
$('#show-comment-<%=@comment.id%>').html("<%= j render 'comments/newcomment' %>");