config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'

  get 'relationships/destroy'

  root to: 'articles#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get get'/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :articles do
    resources :comments
  end

  resources :relationships, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
                                  foreign_key: "followed_id",
                                  dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower 

  has_secure_password
  validates :email, presence: true, uniqueness: true
  validates :name, :password_digest, presence: true
  validates :password, length: {minimum: 8}, on: :create

  mount_uploader :avatar, AvatarUploader

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end

end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:index, :edit, :update, :destroy, :following, :followers]

  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "created user, you're logged in."
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:user] = "Updated user"
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(param[:id])
    if @user.destroy
      flash[:success] = "Deleted user #{@user.name}"
      redirect_to root_path
    else
      flash[:succes] = "Can not delete user, you dont have supper user permission"
    end
  end 
  
  def following
    @user = User.find(params[:id])
    @users = @user.following
    render 'show_follow'
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_follow'
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :avatar)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user != @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user, html: {multipart: true, class: "form-group"} do |f| %>
  <fieldset class = "form-group">
    <div class = "form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control", autofocus: true %>
    </div>
    <div class = "form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>
    </div>
    <div class = "form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>
    </div>
    <div class = "form-group">
      <%= f.file_field :avatar %>
    </div>
  </fieldset>
  <%= f.submit "Resgister", class: "btn btn-info" %>
  
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/edit.html.erb
<h3> Edit user </h3>
<%= render 'form' %>
<%= link_to 'Home', root_path %>

app/views/users/index.html.erb
<p>
<% @users.each do |user| %>
  <%= user.name %><br>
  <%= user.email %>
  <%= link_to 'Show', user %>
  <%= link_to 'Edit', edit_user_path(user) %>

<br><br>
<% end %>

app/views/users/new.html.erb
<h3> Sign up </h3>
<%= render 'form' %>
<%= link_to 'Home', root_path %>

app/views/users/show.html.erb
<br>
<%= image_tag @user.avatar, width: 80, height: 80 %>
<p> Name: <br>
<%= @user.name %>
<p> ID: <br>
<%= @user.id %>
</p>
<p> Email <br>
<%= @user.email %>
</p>
<%= render 'shared/stats' %>

<%= render 'follow_form' if user_signed_in? %>

<%= link_to 'Manager user', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/show_follow.html.erb
<%= @user.name %>
<%= link_to "View my profile", user_path(@user) %>

<% render 'shared/stats' %>
<% if @users.any? %>
  <% @users.each do |user| %>
    <%= user.name  %>
  <% end %>
<% end %>